<a href="https://colab.research.google.com/github/PARTH-SADHU/Python_Projects/blob/master/python_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]],dtype=np.uint8)
print(A)
print(A.shape)
print(A.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
uint8


In [ ]:
A=np.array([[1,2,3,5],[4,5,6,7],[7,8,9,0]],dtype=np.uint8)
print(A)

[[1 2 3 5]
 [4 5 6 7]
 [7 8 9 0]]


In [ ]:
B=np.ones((10,10),dtype=np.uint8)
print(B)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
B=np.ones((5,7),dtype=np.uint8)
print(B*50)

[[50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50]]


In [ ]:
C=np.arange(1,101)
print(C)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
P=np.ones((3,5),dtype=np.uint8)
Q=np.ones((3,8),dtype=np.uint8)

R=np.concatenate([P,Q+3],axis=1)
print(R)

[[1 1 1 1 1 4 4 4 4 4 4 4 4]
 [1 1 1 1 1 4 4 4 4 4 4 4 4]
 [1 1 1 1 1 4 4 4 4 4 4 4 4]]


In [ ]:
P=np.ones((4,8),dtype=np.uint8)
Q=np.ones((3,8),dtype=np.uint8)

R=np.concatenate([P+2,Q],axis=0)
print(R)


[[3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
C=np.ones((5,4),dtype=np.float32)
D=C+2.54
print("This is the value of D-",D
      )

E=D.astype(np.uint8)
print("This is the value of E-",+E)


This is the value of D- [[3.54 3.54 3.54 3.54]
 [3.54 3.54 3.54 3.54]
 [3.54 3.54 3.54 3.54]
 [3.54 3.54 3.54 3.54]
 [3.54 3.54 3.54 3.54]]
This is the value of E- [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
print(np.zeros_like(E))
print(np.ones_like(E))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
randomvals=np.random.rand(5,7)
print(randomvals)

[[0.8489434  0.12820641 0.84366289 0.34279595 0.25213467 0.58600393
  0.07864176]
 [0.26781529 0.24605684 0.92865671 0.8054014  0.02868976 0.55776767
  0.13849821]
 [0.90478098 0.59709429 0.20989594 0.27968971 0.09519559 0.5878567
  0.4527686 ]
 [0.31928866 0.40385791 0.53699389 0.68865681 0.71446378 0.03282826
  0.89243218]
 [0.07467312 0.42283219 0.87136677 0.723652   0.51731185 0.18897341
  0.65325177]]


In [ ]:
randomints=np.random.randint(5,7)
print(randomints)

6


In [ ]:
randomints=np.random.randint(256,size=(50,50))
print(randomints)

[[ 33   8 238 ... 149 195 203]
 [229 245 131 ...  37 123 155]
 [177 122  83 ... 140  78   9]
 ...
 [117 199  54 ... 198 190  76]
 [ 66 124  54 ...  66 218  32]
 [142  11 100 ...  67  93 171]]


In [ ]:
#For all the column values
print(randomints[5,:])

[232   7  21  89 190 178 193  61 230   4 182 254 122  62  97 148  58  65
 179 164  96  14  22  13  99 220  51  28 128 249 189 124 174 117 190  83
 117  23  35 126 156 147 172  51 192 198 214 197 250  99]


In [ ]:
print(randomints[0:5,0:6])
#hw= 500*500 array

[[ 33   8 238   9 100  86]
 [229 245 131 247 204 183]
 [177 122  83 176  59 173]
 [181  46 228 243  69 170]
 [128  95 245 200 205 104]]
